const commonTextStyles = {
  color: '#0019A7',
  fontFamily: 'Comfortaa',
  fontStyle: 'normal',
  fontWeight: '700',
};

const StylesNotifications = {
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  bgGradient: {
    resizeMode: 'contain',
    width: '100%',
    height: '100%',
  },
  viewTtitle: {
    top: 30,
    width: '80%',
    alignSelf: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  title: {
    color: '#0019A7',
    fontFamily: 'Comfortaa',
    fontSize: 24,
    fontStyle: 'normal',
    fontWeight: 700,
  },
  icoRecherche: {
    resizeMode: 'contain',
    width: 30,
    height: 30,
  },
  viewSuggest: {
    alignItems: 'flex-start',
    justifyContent: 'space-evenly',
    top: 20,
    width: 345,
    height: 93,
    alignSelf: 'center',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#0019A7',
    backgroundColor: '#FFF',
  },
  textSuggest: {
    left: 20,
    color: '#0019A7',
    fontFamily: 'Comfortaa',
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: 700,
    letterSpacing: 0.5,
  },
  textSuggestBold: {
    left: 20,
    color: '#0019A7',
    fontFamily: 'Gilroy',
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: 700,
    letterSpacing: 0.5,
  },
  viewScroll: {
    width: '100%',
    alignSelf: 'center',
  },
  scrollView: {
    top: 20,
    height: '68%',
    marginTop: 20,
    flexDirection: 'column',
  },
  dateNotification: {
    marginVertical: 10,
    marginLeft: 20,
    color: '#0019A7',
    fontFamily: 'Gilroy',
    fontWeight: '700',
  },
  boxNotification: {
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    width: 390,
    height: 110,
  },
  notificationAvatar: {
    width: 62.68,
    height: 60,
    resizeMode: 'contain',
    borderRadius: 50,
    borderWidth: 1,
  },
  notificationBoxCol: {
    flexDirection: 'column',
    width: 280,
    height: 90,
  },
  notificationBoxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    height: '25%',
    marginBottom: 10,
  },
  notificationUsername: {
    marginRight: 20,
    color: '#0019A7',
    fontFamily: 'Gilroy',
    fontSize: 20,
    fontStyle: 'normal',
    fontWeight: 700,
  },
  notificationCertified: {
    width: 28,
    height: 28,
    resizeMode: 'contain',
    marginRight: 20,
  },
  notificationPrenium: {
    width: 28,
    height: 28,
    resizeMode: 'contain',
  },
  notificationText: {
    color: '#929EDE',
    fontFamily: 'Comfortaa',
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: 700,
  },
  notificationSeparator: {
    backgroundColor: '#0019A7',
    height: 1,
    width: '90%',
    alignSelf: 'center',
  },
};

export default StylesNotifications;
