const StylesProfileMeRp = {
  container: {
    flex: 1,
    backgroundColor: 'black',
  },
  background: {
    width: 346,
    height: 313,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: '#E5E5E5',
    alignSelf: 'center',
    top: 10,
  },
  boxPreference: {
    position: 'absolute',
    top: 20,
    right: 30,
    width: 30,
    height: 30,
  },
  icoPreference: {
    width: 30,
    height: 30,
  },
  viewCol: {
    position: 'absolute',
    top: 240,
    left: 10,
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  viewCol2: {
    flexDirection: 'column',
    left: 10,
  },
  viewRow: {
    justifyContent: 'space-around',
    flexDirection: 'row',
    left: 10,
  },
  viewRow2: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginTop: 25,
  },
  viewRow3: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    paddingHorizontal: 20,
  },
  viewRow4: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    paddingHorizontal: 20,
    marginTop: 20,
  },
  viewGap: {
    top: 25,
    width: '90%',
    alignSelf: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 10,
    gap: 10,
  },
  userName: {
    fontSize: 24,
    fontFamily: 'Comfortaa-Bold',
    fontWeight: '500',
    color: '#fff',
    letterSpacing: 1,
  },
  icoQuality: {
    top: 5,
    width: 30,
    height: 30,
    left: 35,
  },
  icoMedaille: {
    top: 5,
    left: 45,
    width: 30,
    height: 44,
  },
  userCity: {
    fontSize: 16,
    fontFamily: 'Comfortaa',
    fontWeight: '500',
    color: '#fff',
    letterSpacing: 1,
    left: 10,
  },
  userId: {
    width: 257,
    height: 35,
    color: '#fff',
    fontSize: 15,
    left: 30,
  },
  boxEdit: {
    width: 120,
    height: 30,
    borderRadius: 30,
    right: 35,
    alignItems: 'center',
  },
  txtEdit: {
    fontSize: 15,
    fontFamily: 'Comfortaa-Bold',
    fontWeight: '500',
    color: '#000',
    alignSelf: 'center',
    textAlign: 'center',
  },
  txtTitleAbout: {
    fontFamily: 'Comfortaa-Bold',
    fontWeight: '500',
    color: '#fff',
    fontSize: 20,
    left: 20,
    marginTop: 10,
  },
  txtAbout: {
    fontFamily: 'Comfortaa',
    fontWeight: '500',
    color: '#fff',
    fontSize: 15,
  },
  icoPass: {
    width: 55,
    height: 55,
    bottom: 10,
  },
  txtPass: {
    fontFamily: 'Comfortaa-Bold',
    fontWeight: '500',
    color: '#fff',
    fontSize: 15,
  },
  line: {
    borderBottomWidth: 1,
    borderBottomColor: '#fff',
    bottom: 1,
  },
  line2: {
    height: 1.5,
    backgroundColor: '#fff',
    marginVertical: 2,
    marginHorizontal: 20,
  },
  boxCommunity: {
    width: 33,
    height: 33,
    marginLeft: 60,
    right: 15,
    flexDirection: 'row',
  },
  icoCommunity: {
    width: 33,
    height: 33,
  },
  txtCommunity: {
    fontFamily: 'Comfortaa',
    fontWeight: '500',
    color: '#fff',
    fontSize: 18,
    left: 5,
    bottom: 10,
  },
  boxHeart: {
    width: 33,
    height: 33,
    marginLeft: 30,
    right: 15,
  },
  icoHeart: {
    width: 33,
    height: 33,
  },
  skillTitle: {
    fontFamily: 'Comfortaa',
    fontWeight: '700',
    color: '#fff',
    fontSize: 20,
    left: 20,
    top: 10,
  },
  txtSkill: {
    maxWidth: 200,
    fontFamily: 'Comfortaa-Bold',
    textAlign: 'center',
    fontWeight: '500',
    color: '#000',
    fontSize: 15,
    height: 40,
    borderRadius: 20,
    paddingVertical: 5,
    paddingHorizontal: 20,
    backgroundColor: 'white',
  },
  viewDetails: {
    width: '100%',
    height: 720,
    marginTop: 50,
    backgroundColor: '#fff',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
  },
  viewDetails2: {
    flexDirection: 'row',
    marginTop: 45,
    alignItems: 'center',
  },
  icoDetails: {
    width: 35,
    height: 35,
    marginRight: 20,
    marginLeft: 20,
    resizeMode: 'contain',
  },
  titleDetails: {
    fontFamily: 'Comfortaa',
    fontWeight: '700',
    fontSize: 15,
    color: 'black',
  },
  txtDetails: {
    fontFamily: 'Comfortaa',
    fontWeight: '500',
    fontSize: 14,
    color: 'black',
    marginLeft: 20,
  },
  txtDetails2: {
    fontFamily: 'Gilory',
    fontWeight: '500',
    fontSize: 12,
    color: 'black',
    marginLeft: 20,
  },
};

export default StylesProfileMeRp;
