import {StyleSheet} from 'react-native';

const StylesLoginEmail = StyleSheet.create({
  TextInputNumero: {
    position: 'relative',
    color: '#FFF',
    fontSize: 18,
    alignSelf: 'center',
    width: '80%',
    textAlign: 'center',
    borderWidth: 2,
    borderColor: '#FFF',
    borderRadius: 30,
    padding: 15,
    top: 0,
  },
  textError: {
    color: '#880808',
    width: '70%',
    top: 10,
    fontFamily: 'Comfortaa-Bold',
    fontSize: 12,
    alignSelf: 'center',
    textDecorationLine: 'underline',
    textDecorationColor: '#880808',
  },
  textError2: {
    right: 20,
    width: '60%',
    fontSize: 12,
    color: '#880808',
    alignSelf: 'center',
    textDecorationLine: 'underline',
    textDecorationColor: '#880808',
    fontFamily: 'Comfortaa',
  },
  textWhite: {
    color: '#fff',
    top: 10,
    left: 30,
    width: '80%',
    fontSize: 12,
    alignSelf: 'center',
    fontFamily: 'Comfortaa',
  },
  textWhite2: {
    color: '#fff',
    alignSelf: 'center',
    fontFamily: 'Comfortaa',
    top: 50,
    left: 30,
    width: '80%',
    fontSize: 12,
  },
  TextInputPassword: {
    top: 30,
    color: '#FFF',
    fontSize: 18,
    alignSelf: 'center',
    width: '80%',
    textAlign: 'center',
    borderWidth: 2,
    borderColor: '#FFF',
    borderRadius: 30,
    padding: 15,
  },
});
export default StylesLoginEmail;
