/* eslint-disable prettier/prettier */

const StyleSupprimerCompte = {
  bgGradient: {
    resizeMode: 'contain',
    width: '100%',
    height: '100%',
  },
  title: {
    top: 10,
    color: '#0019A7',
    fontFamily: 'Comfortaa',
    textAlign: 'center',
    fontSize: 24,
    fontWeight: 700,
  },
  separator: {
    backgroundColor: '#0019A7',
    width: 351,
    height: 1,
    alignSelf: 'center',
    top: 40,
  },
  description: {
    color: '#929EDE',
    top: 60,
    width: 320,
    alignSelf: 'center',
    textAlign: 'center',
    fontFamily: 'Comfortaa',
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: 700,
  },
  mettreEnPauseContainer: {
    flexShrink: 0,
    alignSelf: 'center',
    top: 100,
  },
  confirmText: {
    color: '#0019A7',
    textAlign: 'center',
    fontFamily: 'Gilroy',
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: 700,
  },
  switchButton: {
    top: 30,
    alignSelf: 'center',
  },
  progressBarContainer: {
    top: 170,
    flexDirection: 'row',
    alignSelf: 'center',
    width: '80%',
    height: 20,
    borderRadius: 10,
    backgroundColor: '#E0E0E0',
    overflow: 'hidden',
  },
  progressBarBg: {
    height: '100%',
    backgroundColor: '#0019A7',
  },
  progressBarBtn: {
    position: 'absolute',
    width: 20,
    height: 20,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    backgroundColor: '#0019A7',
    justifyContent: 'center',
    alignItems: 'center',
  },
  progressBarContainerText: {
    top: 170,
    height: 26,
    width: '70%',
    alignSelf: 'center',
  },
  progressBarText: {
    fontFamily: 'Gilroy',
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: 700,
  },
  viewItem: {
    flexShrink: 0,
    alignSelf: 'center',
    top: 150,
    marginBottom: 40,
  },
  viewContainerInfo: {
    top: 100,
    width: '100%',
    height: '30%',
    flexDirection: 'column',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  inputNumber: {
    height: 51,
    width: 276,
    margin: 12,
    borderWidth: 1,
    padding: 10,
    borderRadius: 50,
    textAlign: 'center',
    color: '#0019A7',
  },
  confirmButton: {
    width: 276,
    height: 51,
    flexShrink: 0,
    alignSelf: 'center',
    resizeMode: 'contain',
  },
  confirmButtonText: {
    top: -40,
    color: '#FFF',
    textAlign: 'center',
    alignSelf: 'center',
    fontFamily: 'Comfortaa',
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: 700,
  },
  icoInfo: {
    width: 25,
    height: 25,
  },
  textInfo: {
    color: '#0019A7',
    textAlign: 'center',
    fontFamily: 'Comfortaa',
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: 700,
  },
  linkInfo: {
    color: '#0019A7',
    textAlign: 'center',
    fontFamily: 'Comfortaa',
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: 700,
    textDecorationLine: 'underline',
  },
  backButton: {
    width: 331,
    height: 56,
    flexShrink: 0,
    alignSelf: 'center',
  },
  backButtonText: {
    top: -40,
    textAlign: 'center',
    alignSelf: 'center',
    fontFamily: 'Comfortaa',
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: 700,
  },
};

export default StyleSupprimerCompte;
