const StylesPolitique = {
  btnModal: {
    bottom: 280,
    width: '90%',
    flexDirection: 'row',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  icoBtnModal: {
    width: 38,
    height: 41,
    resizeMode: 'contain',
  },
  txtBtnModal: {
    fontFamily: 'Comfortaa',
    fontWeight: '700',
    fontSize: 15,
    color: 'black',
    right: 90,
  },
  plusBtnModal: {
    width: 37,
    height: 37,
    resizeMode: 'contain',
    right: 0,
  },
  containerModal: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnClose: {
    position: 'absolute',
    width: '100%',
    height: '100%',
  },
  viewModal: {
    top: 80,
    width: '100%',
    height: 700,
    backgroundColor: 'white',
    borderTopLeftRadius: 50,
    borderTopRightRadius: 50,
  },
  icoModal: {
    width: 70,
    height: 70,
    top: 30,
    alignSelf: 'center',
    resizeMode: 'contain',
  },
  txtTitleModal: {
    fontFamily: 'Gilroy-Bold',
    fontWeight: '700',
    fontSize: 20,
    color: '#0019A7',
    top: 50,
    alignSelf: 'center',
  },
  subTxtModal: {
    fontFamily: 'Gilroy',
    fontWeight: '700',
    fontSize: 14,
    color: '#0019A7',
    top: 80,
    left: 40,
  },
  txtOptionSelected: {
    fontFamily: 'Comfortaa',
    fontWeight: '500',
    fontSize: 15,
    color: '#0019A7',
    textAlign: 'center',
    width: 276,
    height: 51,
    paddingVertical: 10,
    borderWidth: 2,
    borderColor: '#0019A7',
    borderRadius: 50,
  },
  viewOption: {
    alignItems: 'center',
    flexDirection: 'column',
    justifyContent: 'space-around',
    bottom: 20,
    paddingTop: 20,
    borderWidth: 2,
    borderTopWidth: 0,
    borderBottomLeftWidth: 1,
    borderBottomRightWidth: 1,
    borderColor: '#0019A7',
    width: 276,
    height: 300,
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
    zIndex: 1,
    backgroundColor: '#fff',
  },
  txtOption: {
    fontFamily: 'Comfortaa',
    fontWeight: '700',
    fontSize: 16,
    color: '#0019A7',
    textAlign: 'center',
  },
  icoViewOption: {
    width: 19,
    height: 16,
    left: 20,
    top: 15,
  },
  txtChoice: {
    fontFamily: 'Comfortaa',
    fontWeight: '700',
    fontSize: 12,
    color: '#000',
    left: 40,
  },
};

export default StylesPolitique;
