const StylesCompetence = {
  btnModal: {
    bottom: 180,
    width: '90%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  icoBtnModal: {
    width: 38,
    height: 41,
    resizeMode: 'contain',
  },
  txtBtnModal: {
    fontFamily: 'Comfortaa',
    fontWeight: '700',
    fontSize: 15,
    color: 'black',
    right: 60,
  },
  plusBtnModal: {
    width: 37,
    height: 37,
    resizeMode: 'contain',
  },
  containerModal: {
    height: '100%',
    width: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnClose: {
    position: 'absolute',
    width: '100%',
    height: '100%',
  },
  viewModal: {
    top: 100,
    width: '100%',
    height: 700,
    backgroundColor: 'white',
    borderTopLeftRadius: 50,
    borderTopRightRadius: 50,
  },
  icoModal: {
    width: 84,
    height: 84,
    top: 30,
    alignSelf: 'center',
  },
  txtTitleModal: {
    fontFamily: 'Gilroy-Bold',
    fontWeight: '700',
    fontSize: 20,
    color: '#000',
    top: 50,
    alignSelf: 'center',
  },
  subTxtModal: {
    fontFamily: 'Gilroy',
    fontWeight: '700',
    fontSize: 14,
    color: '#000',
    top: 100,
    left: 40,
  },
  viewRow: {
    flexDirection: 'row',
    alignItems: 'center',
    top: 140,
    width: 345,
    height: 39,
    borderColor: '#000',
    borderWidth: 2,
    borderRadius: 50,
    paddingHorizontal: 20,
  },
  icoInput: {
    width: 20,
    height: 20,
  },
  txtInput: {
    fontSize: 14,
    fontFamily: 'Comfortaa',
    fontWeight: '700',
    color: '#6D6966',
    padding: 5,
    left: 10,
  },
  viewOption: {
    top: 200,
    width: '90%',
    maxHeight: 200,
    alignSelf: 'center',
  },
  viewScroll: {
    flexWrap: 'wrap',
    flexDirection: 'row',
    gap: 20,
    paddingVertical: 20,
    paddingHorizontal: 20,
    justifyContent: 'space-around',
  },
  btnOption: {
    backgroundColor: 'white',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 50,
    borderWidth: 1,
    borderColor: '#000',
    height: 39,
    paddingHorizontal: 20,
  },
  txtOption: {
    fontFamily: 'Gilroy-Bold',
    fontSize: 18,
    textAlign: 'center',
    color: '#000',
  },
  txtChoice: {
    fontFamily: 'Comfortaa',
    fontWeight: '700',
    fontSize: 12,
    color: '#000',
    left: 30,
  },
};

export default StylesCompetence;
