import {StyleSheet} from 'react-native';

const StylesPrenom = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
  },
  bgGradient: {
    resizeMode: 'contain',
    width: '100%',
    height: '100%',
  },
  ViewText: {
    top: 50,
    flexDirection: 'column',
    width: '80%',
    alignSelf: 'center',
    flex: 6,
  },
  TxtTitle: {
    top: 50,
    color: '#FFF',
    textAlign: 'center',
    fontFamily: 'Comfortaa',
    fontSize: 24,
    fontStyle: 'normal',
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  textWhite: {
    top: 100,
    color: '#FFF',
    fontFamily: 'Comfortaa',
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: '700',
    letterSpacing: 1,
  },
  textWhite2: {
    color: '#FFF',
    fontFamily: 'Comfortaa',
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: '700',
  },
  textWhite3: {
    top: 320,
    left: 20,
    color: '#fff',
    fontSize: 12,
    width: '90%',
    height: 200,
    fontFamily: 'Comfortaa',
  },
  textBlue: {
    top: 140,
    color: '#0019A7',
    fontFamily: 'Comfortaa',
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: '700',
    letterSpacing: 1,
    textDecorationLine: 'underline',
  },
  textBlue2: {
    top: 220,
    color: '#0019A7',
    textAlign: 'center',
    fontFamily: 'Comfortaa-Bold',
    fontSize: 18,
    fontWeight: '700',
  },
  ViewRow: {
    top: 180,
    left: 10,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  inputPrenom: {
    height: 40,
    margin: 12,
    borderWidth: 1,
    padding: 10,
    textAlign: 'center',
    fontSize: 15,
    borderRadius: 50,
    borderColor: '#fff',
  },
  inputPseudo: {
    height: 40,
    margin: 12,
    borderWidth: 1,
    padding: 10,
    textAlign: 'center',
    fontSize: 15,
    borderRadius: 50,
    borderColor: '#fff',
  },
  Btn: {
    justifyContent: 'center',
    alignItems: 'center',
    height: 56,
  },
  TxtBtn: {
    color: '#0F0BAE',
    fontSize: 22,
    textAlign: 'center',
    fontFamily: 'Comfortaa',
    zIndex: 1,
    top: 40,
  },
  ImgBtn: {
    height: 56,
    resizeMode: 'contain',
    alignSelf: 'center',
  },
  // Modal
  ViewModal: {
    position: 'absolute',
    top: 210,
    width: '100%',
    height: 620,
    backgroundColor: '#FFF',
    borderTopLeftRadius: 50,
    borderTopRightRadius: 50,
  },
  BtnCloseModal: {
    bottom: 200,
    backgroundColor: 'transparent',
    height: '34%',
    width: '100%',
    position: 'relative',
  },
  icoModal: {
    bottom: 180,
    width: 70,
    height: 70,
    resizeMode: 'contain',
    alignSelf: 'center',
  },
  ViewTextModal: {
    bottom: 180,
    width: '80%',
    alignSelf: 'center',
  },
  ViewModalCol: {
    flexDirection: 'column',
    height: 140,
    justifyContent: 'space-between',
  },
  ViewModalRow: {
    flexDirection: 'row',
  },
  titleModal: {
    color: '#0019A7',
    textAlign: 'center',
    fontFamily: 'Gilroy',
    fontSize: 20,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: 100,
  },
  textModalBlue: {
    color: '#0019A7',
    textAlign: 'left',
    fontFamily: 'Gilroy',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 16,
    marginBottom: 20,
  },
  BlueDot: {
    color: '#0019A7',
    textAlign: 'left',
    fontFamily: 'Gilroy',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 16,
    marginRight: 8,
  },
  SubTextBlue: {
    color: '#0019A7',
    textAlign: 'left',
    fontFamily: 'Gilroy',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 16,
  },
  ImgBtnModal: {
    width: 148,
    height: 56,
    resizeMode: 'contain',
    alignSelf: 'center',
  },
  TextBtnModal: {
    bottom: 40,
    color: '#FFF',
    textAlign: 'center',
    fontFamily: 'Comfortaa',
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: '700',
  },
});

export default StylesPrenom;
