import {StyleSheet} from 'react-native';

const StylesAjoutPhoto = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
  },
  bgGradient: {
    resizeMode: 'contain',
    width: '100%',
    height: '100%',
  },
  ViewText: {
    flex: 1,
    top: 100,
  },
  TxtTitle: {
    top: 20,
    color: '#FFF',
    fontFamily: 'Comfortaa-Bold',
    fontSize: 24,
    fontStyle: 'normal',
    textAlign: 'center',
    fontWeight: '500',
  },
  TxtTitle2: {
    top: 50,
    color: '#fff',
    fontSize: 16,
    width: '100%',
    alignSelf: 'center',
    fontFamily: 'Comfortaa',
    textAlign: 'center',
  },
  imgPhoto: {
    top: 50,
    width: 150,
    height: 150,
    alignSelf: 'center',
    resizeMode: 'contain',
    marginTop: 20,
    borderWidth: 2,
    borderColor: '#0F0BAE',
    borderRadius: 20,
  },
  viewBtn: {
    top: 80,
    height: 200,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  btn: {
    height: 56,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  btn2: {
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
  },
  btn3: {
    top: 160,
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
  },
  imgBtn: {
    top: 18,
    height: 56,
    resizeMode: 'contain',
    alignSelf: 'center',
  },
  imgBtn2: {
    height: 56,
    resizeMode: 'contain',
    alignSelf: 'center',
  },
  textBtn: {
    color: '#fff',
    fontSize: 22,
    textAlign: 'center',
    fontFamily: 'Comfortaa-Bold',
    zIndex: 1,
    bottom: 32,
    left: 20,
  },
  textBtn1: {
    color: '#0F0BAE',
    fontSize: 22,
    zIndex: 1,
    top: 40,
    textAlign: 'center',
    fontFamily: 'Comfortaa-Bold',
  },
  textBtn2: {
    color: '#fff',
    fontSize: 22,
    zIndex: 1,
    bottom: 30,
    textAlign: 'center',
    fontFamily: 'Comfortaa-Bold',
  },
  textBtnBlue: {
    top: 150,
    color: '#0F0BAE',
    fontSize: 16,
    textAlign: 'center',
    textDecorationLine: 'underline',
    fontFamily: 'Comfortaa-Bold',
  },
  centeredView: {
    top: 150,
    flex: 1,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFF',
  },
  icoCadenas: {
    width: 100,
    height: 100,
    bottom: 120,
    resizeMode: 'contain',
  },
  textBlueCenter: {
    bottom: 80,
    color: '#0F0BAE',
    fontSize: 24,
    fontFamily: 'Comfortaa',
    alignSelf: 'center',
    textAlign: 'center',
  },
  textBlueCenter2: {
    bottom: 30,
    color: '#0F0BAE',
    fontSize: 18,
    fontFamily: 'Comfortaa',
    alignSelf: 'center',
    textAlign: 'center',
  },
  rowImg: {
    width: '90%',
    height: 130,
    bottom: 50,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignSelf: 'center',
  },
  imgBlur: {
    width: 100,
    height: 130,
    resizeMode: 'cover',
    borderWidth: 2,
    borderColor: '#0F0BAE',
    borderRadius: 30,
  },
  imgNblur: {
    width: 100,
    height: 130,
    resizeMode: 'cover',
    borderWidth: 2,
    borderColor: '#0F0BAE',
    borderRadius: 30,
  },
});

export default StylesAjoutPhoto;
