import {StyleSheet} from 'react-native';

const StylesEmpreinteVocal = StyleSheet.create({
  bgGradient: {
    flex: 1,
    resizeMode: 'contain',
    width: '100%',
    height: '100%',
  },
  ViewText: {
    flex: 8,
    top: 100,
  },
  TxtTitle: {
    color: '#FFF',
    fontFamily: 'Comfortaa-Bold',
    fontSize: 24,
    fontStyle: 'normal',
    fontWeight: '600',
    textAlign: 'center',
  },
  textWhite: {
    top: 30,
    color: '#FFF',
    fontFamily: 'Comfortaa-Bold',
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: '500',
    alignSelf: 'center',
    width: '70%',
    height: 200,
  },
  viewCol: {
    bottom: 100,
    flexDirection: 'column',
    height: 190,
    justifyContent: 'space-around',
    alignItems: 'center',
    alignSelf: 'center',
  },
  btnVocal: {
    padding: 15,
    borderRadius: 100,
    height: 135,
    width: 135,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: '#0F0BAE',
  },
  viewVocal: {
    backgroundColor: 'white',
    borderRadius: 100,
    height: 118,
    width: 118,
    alignItems: 'center',
    justifyContent: 'center',
  },
  imgVocal: {
    width: 70,
    height: 110,
    alignSelf: 'center',
    resizeMode: 'contain',
  },
  textWhiteCenter: {
    bottom: 110,
    color: '#fff',
    fontSize: 16,
    width: '75%',
    alignSelf: 'center',
    fontFamily: 'Comfortaa',
    textAlign: 'center',
  },
  viewRow: {
    backgroundColor: 'transparent',
    bottom: 100,
    height: 40,
    width: 100,
    flexDirection: 'row',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  btnStop: {
    backgroundColor: '#0019A7',
    width: 30,
    height: 30,
    borderRadius: 10,
  },
  btnRecord: {
    backgroundColor: '#0019A7',
    width: 30,
    height: 30,
    borderRadius: 100,
  },
  icoVocal: {
    width: 30,
    height: 30,
    alignSelf: 'center',
    resizeMode: 'contain',
  },
  viewRow2: {
    bottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    width: '70%',
    alignSelf: 'center',
  },
  textBtn: {
    color: '#fff',
    fontSize: 20,
    textDecorationLine: 'underline',
    textAlign: 'center',
  },
  icoInfo: {
    width: 25,
    height: 25,
    resizeMode: 'contain',
  },
  viewRow3: {
    flexDirection: 'row',
    marginLeft: 50,
    bottom: 10,
  },
  btnInputLang: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 20,
  },
  SelectedImage: {
    width: 20,
    height: 20,
  },
  textBtnInputLang: {
    marginLeft: 10,
    color: '#FFF',
    fontSize: 16,
  },
  textWhite2: {
    color: '#fff',
    fontSize: 12,
    left: 20,
    width: '90%',
    alignSelf: 'center',
    fontFamily: 'Comfortaa',
  },
  btn: {
    top: 16,
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  textBtnBlue: {
    color: '#0F0BAE',
    width: '80%',
    fontSize: 20,
    textAlign: 'center',
    alignSelf: 'center',
    textDecorationLine: 'underline',
  },
  centeredView2: {
    flex: 1,
    top: 200,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFF',
  },
  textBlueCenter: {
    color: '#0F0BAE',
    bottom: 200,
    fontSize: 18,
    fontFamily: 'Comfortaa',
    alignSelf: 'center',
    textAlign: 'center',
  },
  icoInfo2: {
    bottom: 160,
    width: 30,
    height: 30,
    resizeMode: 'contain',
    alignSelf: 'center',
  },
  textBlue: {
    bottom: 130,
    width: '80%',
    color: '#0F0BAE',
    fontSize: 18,
    fontFamily: 'Comfortaa',
    textAlign: 'left',
    alignSelf: 'center',
  },
  textBlueBold: {
    color: '#0F0BAE',
    fontSize: 20,
    fontWeight: '800',
    fontFamily: 'Comfortaa',
  },
  closeModal: {
    position: 'absolute',
    height: 200,
    width: '100%',
    top: -200,
  },
});

export default StylesEmpreinteVocal;
