import {StyleSheet} from 'react-native';

const StylesLangParler = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
  },
  bgGradient: {
    resizeMode: 'contain',
    width: '100%',
    height: '100%',
  },
  ViewText: {
    flex: 1,
    top: 100,
  },
  TxtTitle: {
    top: 40,
    color: '#fff',
    textAlign: 'center',
    alignSelf: 'center',
    fontFamily: 'Comfortaa',
    fontSize: 20,
  },
  line: {
    top: 15,
    backgroundColor: '#0F0BAE',
    height: 2,
    width: '70%',
    alignSelf: 'center',
    margin: 15,
  },
  modal: {
    backgroundColor: 'transparent',
    borderRadius: 10,
    padding: 10,
    width: '60%',
    alignSelf: 'center',
    marginTop: '50%',
    top: 340,
  },
  item: {
    fontSize: 18,
    padding: 10,
  },
  ViewInputRadioLang: {
    flexDirection: 'row',
    marginLeft: 50,
    bottom: 20,
  },
  btnInputLang: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 20,
  },
  SelectedImage: {
    width: 20,
    height: 20,
  },
  textBtnInputLang: {
    marginLeft: 10,
    color: '#FFF',
    fontSize: 16,
  },
  textWhite: {
    color: '#fff',
    left: 30,
    fontSize: 12,
    width: '90%',
    alignSelf: 'center',
    fontFamily: 'Comfortaa',
  },
  textWhiteCenter: {
    color: '#fff',
    textAlign: 'center',
    fontFamily: 'Comfortaa',
    fontSize: 20,
  },
  textWhiteCenter2: {
    color: '#fff',
    fontSize: 16,
    width: '75%',
    alignSelf: 'center',
    fontFamily: 'Comfortaa',
    textAlign: 'center',
    bottom: 100,
  },
  textGrayCenter: {
    color: '#cacaca',
    textAlign: 'center',
    fontFamily: 'Comfortaa',
    fontSize: 20,
  },
  btnModal: {
    backgroundColor: 'transparent',
    borderRadius: 50,
    borderWidth: 2,
    bottom: 120,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: '#cacaca',
    alignSelf: 'center',
    height: 60,
    width: '80%',
  },
  blurView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  absoluteBlur: {
    position: 'absolute',
    top: 510,
    height: 90,
    width: '100%',
    alignSelf: 'center',
    borderRadius: 50,
  },
  textGray: {
    color: '#cacaca',
    fontSize: 16,
  },
  ViewBtn: {
    flex: 1,
    top: 50,
    height: 56,
    justifyContent: 'center',
    alignItems: 'center',
  },
  imgBtn: {
    height: 56,
    flexShrink: 0,
    alignSelf: 'center',
    resizeMode: 'contain',
    bottom: 17,
  },
  TxtBtn: {
    color: '#0F0BAE',
    fontSize: 22,
    textAlign: 'center',
    fontFamily: 'Comfortaa',
    top: 24,
    zIndex: 1,
  },
});

export default StylesLangParler;
